timezone: Europe/London
keep_files:  ['.git']
redcarpet:
  extensions: ['autolink', 'strikethrough', 'superscript']
title: Iain Sproat
author:
  name: Iain Sproat
  email: iainsproat@gmail.com
  twitter: iainsproat
  github: iainsproat
sass:
    sass_dir: _sass
